version: '2'
services:
  frontend:
    container_name: frontend
    image: oussamagharbi/chat-app-front:2.0
    ports:
      - 3000:80
    
  backend:
    container_name: backend
    image: oussamagharbi/chat-app-back:2.0
    ports:
      - 5000:5000
    
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    
    volumes:
      - ./containers_backups/mongo:/data/db
  mongo-express:
    container_name: express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      

volumes:
  mongo:
    driver: local
  jenkins:
    driver: local
